
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ServiceAccount` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ServiceAccount
 * 
 */
export type ServiceAccountModel = runtime.Types.Result.DefaultSelection<Prisma.$ServiceAccountPayload>

export type AggregateServiceAccount = {
  _count: ServiceAccountCountAggregateOutputType | null
  _min: ServiceAccountMinAggregateOutputType | null
  _max: ServiceAccountMaxAggregateOutputType | null
}

export type ServiceAccountMinAggregateOutputType = {
  id: string | null
  type: string | null
  username: string | null
  passwordEncrypted: string | null
  ownerUserId: string | null
}

export type ServiceAccountMaxAggregateOutputType = {
  id: string | null
  type: string | null
  username: string | null
  passwordEncrypted: string | null
  ownerUserId: string | null
}

export type ServiceAccountCountAggregateOutputType = {
  id: number
  type: number
  username: number
  passwordEncrypted: number
  ownerUserId: number
  _all: number
}


export type ServiceAccountMinAggregateInputType = {
  id?: true
  type?: true
  username?: true
  passwordEncrypted?: true
  ownerUserId?: true
}

export type ServiceAccountMaxAggregateInputType = {
  id?: true
  type?: true
  username?: true
  passwordEncrypted?: true
  ownerUserId?: true
}

export type ServiceAccountCountAggregateInputType = {
  id?: true
  type?: true
  username?: true
  passwordEncrypted?: true
  ownerUserId?: true
  _all?: true
}

export type ServiceAccountAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceAccount to aggregate.
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccounts to fetch.
   */
  orderBy?: Prisma.ServiceAccountOrderByWithRelationInput | Prisma.ServiceAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ServiceAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ServiceAccounts
  **/
  _count?: true | ServiceAccountCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ServiceAccountMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ServiceAccountMaxAggregateInputType
}

export type GetServiceAccountAggregateType<T extends ServiceAccountAggregateArgs> = {
      [P in keyof T & keyof AggregateServiceAccount]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateServiceAccount[P]>
    : Prisma.GetScalarType<T[P], AggregateServiceAccount[P]>
}




export type ServiceAccountGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ServiceAccountWhereInput
  orderBy?: Prisma.ServiceAccountOrderByWithAggregationInput | Prisma.ServiceAccountOrderByWithAggregationInput[]
  by: Prisma.ServiceAccountScalarFieldEnum[] | Prisma.ServiceAccountScalarFieldEnum
  having?: Prisma.ServiceAccountScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ServiceAccountCountAggregateInputType | true
  _min?: ServiceAccountMinAggregateInputType
  _max?: ServiceAccountMaxAggregateInputType
}

export type ServiceAccountGroupByOutputType = {
  id: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUserId: string
  _count: ServiceAccountCountAggregateOutputType | null
  _min: ServiceAccountMinAggregateOutputType | null
  _max: ServiceAccountMaxAggregateOutputType | null
}

type GetServiceAccountGroupByPayload<T extends ServiceAccountGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ServiceAccountGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ServiceAccountGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ServiceAccountGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ServiceAccountGroupByOutputType[P]>
      }
    >
  >



export type ServiceAccountWhereInput = {
  AND?: Prisma.ServiceAccountWhereInput | Prisma.ServiceAccountWhereInput[]
  OR?: Prisma.ServiceAccountWhereInput[]
  NOT?: Prisma.ServiceAccountWhereInput | Prisma.ServiceAccountWhereInput[]
  id?: Prisma.StringFilter<"ServiceAccount"> | string
  type?: Prisma.StringFilter<"ServiceAccount"> | string
  username?: Prisma.StringFilter<"ServiceAccount"> | string
  passwordEncrypted?: Prisma.StringFilter<"ServiceAccount"> | string
  ownerUserId?: Prisma.StringFilter<"ServiceAccount"> | string
  ownerUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  garminProfiles?: Prisma.SyncProfileListRelationFilter
  trainerroadProfiles?: Prisma.SyncProfileListRelationFilter
}

export type ServiceAccountOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  username?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  ownerUser?: Prisma.UserOrderByWithRelationInput
  garminProfiles?: Prisma.SyncProfileOrderByRelationAggregateInput
  trainerroadProfiles?: Prisma.SyncProfileOrderByRelationAggregateInput
}

export type ServiceAccountWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ServiceAccountWhereInput | Prisma.ServiceAccountWhereInput[]
  OR?: Prisma.ServiceAccountWhereInput[]
  NOT?: Prisma.ServiceAccountWhereInput | Prisma.ServiceAccountWhereInput[]
  type?: Prisma.StringFilter<"ServiceAccount"> | string
  username?: Prisma.StringFilter<"ServiceAccount"> | string
  passwordEncrypted?: Prisma.StringFilter<"ServiceAccount"> | string
  ownerUserId?: Prisma.StringFilter<"ServiceAccount"> | string
  ownerUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  garminProfiles?: Prisma.SyncProfileListRelationFilter
  trainerroadProfiles?: Prisma.SyncProfileListRelationFilter
}, "id">

export type ServiceAccountOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  username?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  _count?: Prisma.ServiceAccountCountOrderByAggregateInput
  _max?: Prisma.ServiceAccountMaxOrderByAggregateInput
  _min?: Prisma.ServiceAccountMinOrderByAggregateInput
}

export type ServiceAccountScalarWhereWithAggregatesInput = {
  AND?: Prisma.ServiceAccountScalarWhereWithAggregatesInput | Prisma.ServiceAccountScalarWhereWithAggregatesInput[]
  OR?: Prisma.ServiceAccountScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ServiceAccountScalarWhereWithAggregatesInput | Prisma.ServiceAccountScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ServiceAccount"> | string
  type?: Prisma.StringWithAggregatesFilter<"ServiceAccount"> | string
  username?: Prisma.StringWithAggregatesFilter<"ServiceAccount"> | string
  passwordEncrypted?: Prisma.StringWithAggregatesFilter<"ServiceAccount"> | string
  ownerUserId?: Prisma.StringWithAggregatesFilter<"ServiceAccount"> | string
}

export type ServiceAccountCreateInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUser: Prisma.UserCreateNestedOneWithoutServiceAccountsInput
  garminProfiles?: Prisma.SyncProfileCreateNestedManyWithoutGarminAccountInput
  trainerroadProfiles?: Prisma.SyncProfileCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountUncheckedCreateInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUserId: string
  garminProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutGarminAccountInput
  trainerroadProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutServiceAccountsNestedInput
  garminProfiles?: Prisma.SyncProfileUpdateManyWithoutGarminAccountNestedInput
  trainerroadProfiles?: Prisma.SyncProfileUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  garminProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutGarminAccountNestedInput
  trainerroadProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountCreateManyInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUserId: string
}

export type ServiceAccountUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ServiceAccountUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ServiceAccountListRelationFilter = {
  every?: Prisma.ServiceAccountWhereInput
  some?: Prisma.ServiceAccountWhereInput
  none?: Prisma.ServiceAccountWhereInput
}

export type ServiceAccountOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ServiceAccountCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  username?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
}

export type ServiceAccountMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  username?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
}

export type ServiceAccountMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  username?: Prisma.SortOrder
  passwordEncrypted?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
}

export type ServiceAccountNullableScalarRelationFilter = {
  is?: Prisma.ServiceAccountWhereInput | null
  isNot?: Prisma.ServiceAccountWhereInput | null
}

export type ServiceAccountCreateNestedManyWithoutOwnerUserInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput> | Prisma.ServiceAccountCreateWithoutOwnerUserInput[] | Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput | Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput[]
  createMany?: Prisma.ServiceAccountCreateManyOwnerUserInputEnvelope
  connect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
}

export type ServiceAccountUncheckedCreateNestedManyWithoutOwnerUserInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput> | Prisma.ServiceAccountCreateWithoutOwnerUserInput[] | Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput | Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput[]
  createMany?: Prisma.ServiceAccountCreateManyOwnerUserInputEnvelope
  connect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
}

export type ServiceAccountUpdateManyWithoutOwnerUserNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput> | Prisma.ServiceAccountCreateWithoutOwnerUserInput[] | Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput | Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput[]
  upsert?: Prisma.ServiceAccountUpsertWithWhereUniqueWithoutOwnerUserInput | Prisma.ServiceAccountUpsertWithWhereUniqueWithoutOwnerUserInput[]
  createMany?: Prisma.ServiceAccountCreateManyOwnerUserInputEnvelope
  set?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  delete?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  connect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  update?: Prisma.ServiceAccountUpdateWithWhereUniqueWithoutOwnerUserInput | Prisma.ServiceAccountUpdateWithWhereUniqueWithoutOwnerUserInput[]
  updateMany?: Prisma.ServiceAccountUpdateManyWithWhereWithoutOwnerUserInput | Prisma.ServiceAccountUpdateManyWithWhereWithoutOwnerUserInput[]
  deleteMany?: Prisma.ServiceAccountScalarWhereInput | Prisma.ServiceAccountScalarWhereInput[]
}

export type ServiceAccountUncheckedUpdateManyWithoutOwnerUserNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput> | Prisma.ServiceAccountCreateWithoutOwnerUserInput[] | Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput | Prisma.ServiceAccountCreateOrConnectWithoutOwnerUserInput[]
  upsert?: Prisma.ServiceAccountUpsertWithWhereUniqueWithoutOwnerUserInput | Prisma.ServiceAccountUpsertWithWhereUniqueWithoutOwnerUserInput[]
  createMany?: Prisma.ServiceAccountCreateManyOwnerUserInputEnvelope
  set?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  disconnect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  delete?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  connect?: Prisma.ServiceAccountWhereUniqueInput | Prisma.ServiceAccountWhereUniqueInput[]
  update?: Prisma.ServiceAccountUpdateWithWhereUniqueWithoutOwnerUserInput | Prisma.ServiceAccountUpdateWithWhereUniqueWithoutOwnerUserInput[]
  updateMany?: Prisma.ServiceAccountUpdateManyWithWhereWithoutOwnerUserInput | Prisma.ServiceAccountUpdateManyWithWhereWithoutOwnerUserInput[]
  deleteMany?: Prisma.ServiceAccountScalarWhereInput | Prisma.ServiceAccountScalarWhereInput[]
}

export type ServiceAccountCreateNestedOneWithoutGarminProfilesInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutGarminProfilesInput>
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutGarminProfilesInput
  connect?: Prisma.ServiceAccountWhereUniqueInput
}

export type ServiceAccountCreateNestedOneWithoutTrainerroadProfilesInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutTrainerroadProfilesInput>
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutTrainerroadProfilesInput
  connect?: Prisma.ServiceAccountWhereUniqueInput
}

export type ServiceAccountUpdateOneWithoutGarminProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutGarminProfilesInput>
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutGarminProfilesInput
  upsert?: Prisma.ServiceAccountUpsertWithoutGarminProfilesInput
  disconnect?: Prisma.ServiceAccountWhereInput | boolean
  delete?: Prisma.ServiceAccountWhereInput | boolean
  connect?: Prisma.ServiceAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceAccountUpdateToOneWithWhereWithoutGarminProfilesInput, Prisma.ServiceAccountUpdateWithoutGarminProfilesInput>, Prisma.ServiceAccountUncheckedUpdateWithoutGarminProfilesInput>
}

export type ServiceAccountUpdateOneWithoutTrainerroadProfilesNestedInput = {
  create?: Prisma.XOR<Prisma.ServiceAccountCreateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutTrainerroadProfilesInput>
  connectOrCreate?: Prisma.ServiceAccountCreateOrConnectWithoutTrainerroadProfilesInput
  upsert?: Prisma.ServiceAccountUpsertWithoutTrainerroadProfilesInput
  disconnect?: Prisma.ServiceAccountWhereInput | boolean
  delete?: Prisma.ServiceAccountWhereInput | boolean
  connect?: Prisma.ServiceAccountWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ServiceAccountUpdateToOneWithWhereWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUpdateWithoutTrainerroadProfilesInput>, Prisma.ServiceAccountUncheckedUpdateWithoutTrainerroadProfilesInput>
}

export type ServiceAccountCreateWithoutOwnerUserInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  garminProfiles?: Prisma.SyncProfileCreateNestedManyWithoutGarminAccountInput
  trainerroadProfiles?: Prisma.SyncProfileCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountUncheckedCreateWithoutOwnerUserInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  garminProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutGarminAccountInput
  trainerroadProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountCreateOrConnectWithoutOwnerUserInput = {
  where: Prisma.ServiceAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput>
}

export type ServiceAccountCreateManyOwnerUserInputEnvelope = {
  data: Prisma.ServiceAccountCreateManyOwnerUserInput | Prisma.ServiceAccountCreateManyOwnerUserInput[]
}

export type ServiceAccountUpsertWithWhereUniqueWithoutOwnerUserInput = {
  where: Prisma.ServiceAccountWhereUniqueInput
  update: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedUpdateWithoutOwnerUserInput>
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedCreateWithoutOwnerUserInput>
}

export type ServiceAccountUpdateWithWhereUniqueWithoutOwnerUserInput = {
  where: Prisma.ServiceAccountWhereUniqueInput
  data: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutOwnerUserInput, Prisma.ServiceAccountUncheckedUpdateWithoutOwnerUserInput>
}

export type ServiceAccountUpdateManyWithWhereWithoutOwnerUserInput = {
  where: Prisma.ServiceAccountScalarWhereInput
  data: Prisma.XOR<Prisma.ServiceAccountUpdateManyMutationInput, Prisma.ServiceAccountUncheckedUpdateManyWithoutOwnerUserInput>
}

export type ServiceAccountScalarWhereInput = {
  AND?: Prisma.ServiceAccountScalarWhereInput | Prisma.ServiceAccountScalarWhereInput[]
  OR?: Prisma.ServiceAccountScalarWhereInput[]
  NOT?: Prisma.ServiceAccountScalarWhereInput | Prisma.ServiceAccountScalarWhereInput[]
  id?: Prisma.StringFilter<"ServiceAccount"> | string
  type?: Prisma.StringFilter<"ServiceAccount"> | string
  username?: Prisma.StringFilter<"ServiceAccount"> | string
  passwordEncrypted?: Prisma.StringFilter<"ServiceAccount"> | string
  ownerUserId?: Prisma.StringFilter<"ServiceAccount"> | string
}

export type ServiceAccountCreateWithoutGarminProfilesInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUser: Prisma.UserCreateNestedOneWithoutServiceAccountsInput
  trainerroadProfiles?: Prisma.SyncProfileCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountUncheckedCreateWithoutGarminProfilesInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUserId: string
  trainerroadProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutTrainerroadAccountInput
}

export type ServiceAccountCreateOrConnectWithoutGarminProfilesInput = {
  where: Prisma.ServiceAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutGarminProfilesInput>
}

export type ServiceAccountCreateWithoutTrainerroadProfilesInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUser: Prisma.UserCreateNestedOneWithoutServiceAccountsInput
  garminProfiles?: Prisma.SyncProfileCreateNestedManyWithoutGarminAccountInput
}

export type ServiceAccountUncheckedCreateWithoutTrainerroadProfilesInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
  ownerUserId: string
  garminProfiles?: Prisma.SyncProfileUncheckedCreateNestedManyWithoutGarminAccountInput
}

export type ServiceAccountCreateOrConnectWithoutTrainerroadProfilesInput = {
  where: Prisma.ServiceAccountWhereUniqueInput
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutTrainerroadProfilesInput>
}

export type ServiceAccountUpsertWithoutGarminProfilesInput = {
  update: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedUpdateWithoutGarminProfilesInput>
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutGarminProfilesInput>
  where?: Prisma.ServiceAccountWhereInput
}

export type ServiceAccountUpdateToOneWithWhereWithoutGarminProfilesInput = {
  where?: Prisma.ServiceAccountWhereInput
  data: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutGarminProfilesInput, Prisma.ServiceAccountUncheckedUpdateWithoutGarminProfilesInput>
}

export type ServiceAccountUpdateWithoutGarminProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutServiceAccountsNestedInput
  trainerroadProfiles?: Prisma.SyncProfileUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountUncheckedUpdateWithoutGarminProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  trainerroadProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountUpsertWithoutTrainerroadProfilesInput = {
  update: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedUpdateWithoutTrainerroadProfilesInput>
  create: Prisma.XOR<Prisma.ServiceAccountCreateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedCreateWithoutTrainerroadProfilesInput>
  where?: Prisma.ServiceAccountWhereInput
}

export type ServiceAccountUpdateToOneWithWhereWithoutTrainerroadProfilesInput = {
  where?: Prisma.ServiceAccountWhereInput
  data: Prisma.XOR<Prisma.ServiceAccountUpdateWithoutTrainerroadProfilesInput, Prisma.ServiceAccountUncheckedUpdateWithoutTrainerroadProfilesInput>
}

export type ServiceAccountUpdateWithoutTrainerroadProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutServiceAccountsNestedInput
  garminProfiles?: Prisma.SyncProfileUpdateManyWithoutGarminAccountNestedInput
}

export type ServiceAccountUncheckedUpdateWithoutTrainerroadProfilesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  garminProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutGarminAccountNestedInput
}

export type ServiceAccountCreateManyOwnerUserInput = {
  id?: string
  type: string
  username: string
  passwordEncrypted: string
}

export type ServiceAccountUpdateWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  garminProfiles?: Prisma.SyncProfileUpdateManyWithoutGarminAccountNestedInput
  trainerroadProfiles?: Prisma.SyncProfileUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountUncheckedUpdateWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
  garminProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutGarminAccountNestedInput
  trainerroadProfiles?: Prisma.SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountNestedInput
}

export type ServiceAccountUncheckedUpdateManyWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  username?: Prisma.StringFieldUpdateOperationsInput | string
  passwordEncrypted?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ServiceAccountCountOutputType
 */

export type ServiceAccountCountOutputType = {
  garminProfiles: number
  trainerroadProfiles: number
}

export type ServiceAccountCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  garminProfiles?: boolean | ServiceAccountCountOutputTypeCountGarminProfilesArgs
  trainerroadProfiles?: boolean | ServiceAccountCountOutputTypeCountTrainerroadProfilesArgs
}

/**
 * ServiceAccountCountOutputType without action
 */
export type ServiceAccountCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccountCountOutputType
   */
  select?: Prisma.ServiceAccountCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ServiceAccountCountOutputType without action
 */
export type ServiceAccountCountOutputTypeCountGarminProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncProfileWhereInput
}

/**
 * ServiceAccountCountOutputType without action
 */
export type ServiceAccountCountOutputTypeCountTrainerroadProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncProfileWhereInput
}


export type ServiceAccountSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  username?: boolean
  passwordEncrypted?: boolean
  ownerUserId?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminProfiles?: boolean | Prisma.ServiceAccount$garminProfilesArgs<ExtArgs>
  trainerroadProfiles?: boolean | Prisma.ServiceAccount$trainerroadProfilesArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceAccountCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccount"]>

export type ServiceAccountSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  username?: boolean
  passwordEncrypted?: boolean
  ownerUserId?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccount"]>

export type ServiceAccountSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  username?: boolean
  passwordEncrypted?: boolean
  ownerUserId?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["serviceAccount"]>

export type ServiceAccountSelectScalar = {
  id?: boolean
  type?: boolean
  username?: boolean
  passwordEncrypted?: boolean
  ownerUserId?: boolean
}

export type ServiceAccountOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "username" | "passwordEncrypted" | "ownerUserId", ExtArgs["result"]["serviceAccount"]>
export type ServiceAccountInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminProfiles?: boolean | Prisma.ServiceAccount$garminProfilesArgs<ExtArgs>
  trainerroadProfiles?: boolean | Prisma.ServiceAccount$trainerroadProfilesArgs<ExtArgs>
  _count?: boolean | Prisma.ServiceAccountCountOutputTypeDefaultArgs<ExtArgs>
}
export type ServiceAccountIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ServiceAccountIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ServiceAccountPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ServiceAccount"
  objects: {
    ownerUser: Prisma.$UserPayload<ExtArgs>
    garminProfiles: Prisma.$SyncProfilePayload<ExtArgs>[]
    trainerroadProfiles: Prisma.$SyncProfilePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    username: string
    passwordEncrypted: string
    ownerUserId: string
  }, ExtArgs["result"]["serviceAccount"]>
  composites: {}
}

export type ServiceAccountGetPayload<S extends boolean | null | undefined | ServiceAccountDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload, S>

export type ServiceAccountCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ServiceAccountFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ServiceAccountCountAggregateInputType | true
  }

export interface ServiceAccountDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ServiceAccount'], meta: { name: 'ServiceAccount' } }
  /**
   * Find zero or one ServiceAccount that matches the filter.
   * @param {ServiceAccountFindUniqueArgs} args - Arguments to find a ServiceAccount
   * @example
   * // Get one ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ServiceAccountFindUniqueArgs>(args: Prisma.SelectSubset<T, ServiceAccountFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ServiceAccount that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ServiceAccountFindUniqueOrThrowArgs} args - Arguments to find a ServiceAccount
   * @example
   * // Get one ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ServiceAccountFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ServiceAccountFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceAccount that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountFindFirstArgs} args - Arguments to find a ServiceAccount
   * @example
   * // Get one ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ServiceAccountFindFirstArgs>(args?: Prisma.SelectSubset<T, ServiceAccountFindFirstArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ServiceAccount that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountFindFirstOrThrowArgs} args - Arguments to find a ServiceAccount
   * @example
   * // Get one ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ServiceAccountFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ServiceAccountFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ServiceAccounts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ServiceAccounts
   * const serviceAccounts = await prisma.serviceAccount.findMany()
   * 
   * // Get first 10 ServiceAccounts
   * const serviceAccounts = await prisma.serviceAccount.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const serviceAccountWithIdOnly = await prisma.serviceAccount.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ServiceAccountFindManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ServiceAccount.
   * @param {ServiceAccountCreateArgs} args - Arguments to create a ServiceAccount.
   * @example
   * // Create one ServiceAccount
   * const ServiceAccount = await prisma.serviceAccount.create({
   *   data: {
   *     // ... data to create a ServiceAccount
   *   }
   * })
   * 
   */
  create<T extends ServiceAccountCreateArgs>(args: Prisma.SelectSubset<T, ServiceAccountCreateArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ServiceAccounts.
   * @param {ServiceAccountCreateManyArgs} args - Arguments to create many ServiceAccounts.
   * @example
   * // Create many ServiceAccounts
   * const serviceAccount = await prisma.serviceAccount.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ServiceAccountCreateManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ServiceAccounts and returns the data saved in the database.
   * @param {ServiceAccountCreateManyAndReturnArgs} args - Arguments to create many ServiceAccounts.
   * @example
   * // Create many ServiceAccounts
   * const serviceAccount = await prisma.serviceAccount.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ServiceAccounts and only return the `id`
   * const serviceAccountWithIdOnly = await prisma.serviceAccount.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ServiceAccountCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ServiceAccountCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ServiceAccount.
   * @param {ServiceAccountDeleteArgs} args - Arguments to delete one ServiceAccount.
   * @example
   * // Delete one ServiceAccount
   * const ServiceAccount = await prisma.serviceAccount.delete({
   *   where: {
   *     // ... filter to delete one ServiceAccount
   *   }
   * })
   * 
   */
  delete<T extends ServiceAccountDeleteArgs>(args: Prisma.SelectSubset<T, ServiceAccountDeleteArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ServiceAccount.
   * @param {ServiceAccountUpdateArgs} args - Arguments to update one ServiceAccount.
   * @example
   * // Update one ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ServiceAccountUpdateArgs>(args: Prisma.SelectSubset<T, ServiceAccountUpdateArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ServiceAccounts.
   * @param {ServiceAccountDeleteManyArgs} args - Arguments to filter ServiceAccounts to delete.
   * @example
   * // Delete a few ServiceAccounts
   * const { count } = await prisma.serviceAccount.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ServiceAccountDeleteManyArgs>(args?: Prisma.SelectSubset<T, ServiceAccountDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ServiceAccounts
   * const serviceAccount = await prisma.serviceAccount.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ServiceAccountUpdateManyArgs>(args: Prisma.SelectSubset<T, ServiceAccountUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ServiceAccounts and returns the data updated in the database.
   * @param {ServiceAccountUpdateManyAndReturnArgs} args - Arguments to update many ServiceAccounts.
   * @example
   * // Update many ServiceAccounts
   * const serviceAccount = await prisma.serviceAccount.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ServiceAccounts and only return the `id`
   * const serviceAccountWithIdOnly = await prisma.serviceAccount.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ServiceAccountUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ServiceAccountUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ServiceAccount.
   * @param {ServiceAccountUpsertArgs} args - Arguments to update or create a ServiceAccount.
   * @example
   * // Update or create a ServiceAccount
   * const serviceAccount = await prisma.serviceAccount.upsert({
   *   create: {
   *     // ... data to create a ServiceAccount
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ServiceAccount we want to update
   *   }
   * })
   */
  upsert<T extends ServiceAccountUpsertArgs>(args: Prisma.SelectSubset<T, ServiceAccountUpsertArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ServiceAccounts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountCountArgs} args - Arguments to filter ServiceAccounts to count.
   * @example
   * // Count the number of ServiceAccounts
   * const count = await prisma.serviceAccount.count({
   *   where: {
   *     // ... the filter for the ServiceAccounts we want to count
   *   }
   * })
  **/
  count<T extends ServiceAccountCountArgs>(
    args?: Prisma.Subset<T, ServiceAccountCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ServiceAccountCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ServiceAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ServiceAccountAggregateArgs>(args: Prisma.Subset<T, ServiceAccountAggregateArgs>): Prisma.PrismaPromise<GetServiceAccountAggregateType<T>>

  /**
   * Group by ServiceAccount.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ServiceAccountGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ServiceAccountGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ServiceAccountGroupByArgs['orderBy'] }
      : { orderBy?: ServiceAccountGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ServiceAccountGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetServiceAccountGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ServiceAccount model
 */
readonly fields: ServiceAccountFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ServiceAccount.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ServiceAccountClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ownerUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  garminProfiles<T extends Prisma.ServiceAccount$garminProfilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceAccount$garminProfilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  trainerroadProfiles<T extends Prisma.ServiceAccount$trainerroadProfilesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceAccount$trainerroadProfilesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ServiceAccount model
 */
export interface ServiceAccountFieldRefs {
  readonly id: Prisma.FieldRef<"ServiceAccount", 'String'>
  readonly type: Prisma.FieldRef<"ServiceAccount", 'String'>
  readonly username: Prisma.FieldRef<"ServiceAccount", 'String'>
  readonly passwordEncrypted: Prisma.FieldRef<"ServiceAccount", 'String'>
  readonly ownerUserId: Prisma.FieldRef<"ServiceAccount", 'String'>
}
    

// Custom InputTypes
/**
 * ServiceAccount findUnique
 */
export type ServiceAccountFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccount to fetch.
   */
  where: Prisma.ServiceAccountWhereUniqueInput
}

/**
 * ServiceAccount findUniqueOrThrow
 */
export type ServiceAccountFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccount to fetch.
   */
  where: Prisma.ServiceAccountWhereUniqueInput
}

/**
 * ServiceAccount findFirst
 */
export type ServiceAccountFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccount to fetch.
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccounts to fetch.
   */
  orderBy?: Prisma.ServiceAccountOrderByWithRelationInput | Prisma.ServiceAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceAccounts.
   */
  cursor?: Prisma.ServiceAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceAccounts.
   */
  distinct?: Prisma.ServiceAccountScalarFieldEnum | Prisma.ServiceAccountScalarFieldEnum[]
}

/**
 * ServiceAccount findFirstOrThrow
 */
export type ServiceAccountFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccount to fetch.
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccounts to fetch.
   */
  orderBy?: Prisma.ServiceAccountOrderByWithRelationInput | Prisma.ServiceAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ServiceAccounts.
   */
  cursor?: Prisma.ServiceAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccounts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ServiceAccounts.
   */
  distinct?: Prisma.ServiceAccountScalarFieldEnum | Prisma.ServiceAccountScalarFieldEnum[]
}

/**
 * ServiceAccount findMany
 */
export type ServiceAccountFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter, which ServiceAccounts to fetch.
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ServiceAccounts to fetch.
   */
  orderBy?: Prisma.ServiceAccountOrderByWithRelationInput | Prisma.ServiceAccountOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ServiceAccounts.
   */
  cursor?: Prisma.ServiceAccountWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ServiceAccounts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ServiceAccounts.
   */
  skip?: number
  distinct?: Prisma.ServiceAccountScalarFieldEnum | Prisma.ServiceAccountScalarFieldEnum[]
}

/**
 * ServiceAccount create
 */
export type ServiceAccountCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * The data needed to create a ServiceAccount.
   */
  data: Prisma.XOR<Prisma.ServiceAccountCreateInput, Prisma.ServiceAccountUncheckedCreateInput>
}

/**
 * ServiceAccount createMany
 */
export type ServiceAccountCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ServiceAccounts.
   */
  data: Prisma.ServiceAccountCreateManyInput | Prisma.ServiceAccountCreateManyInput[]
}

/**
 * ServiceAccount createManyAndReturn
 */
export type ServiceAccountCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * The data used to create many ServiceAccounts.
   */
  data: Prisma.ServiceAccountCreateManyInput | Prisma.ServiceAccountCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceAccount update
 */
export type ServiceAccountUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * The data needed to update a ServiceAccount.
   */
  data: Prisma.XOR<Prisma.ServiceAccountUpdateInput, Prisma.ServiceAccountUncheckedUpdateInput>
  /**
   * Choose, which ServiceAccount to update.
   */
  where: Prisma.ServiceAccountWhereUniqueInput
}

/**
 * ServiceAccount updateMany
 */
export type ServiceAccountUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ServiceAccounts.
   */
  data: Prisma.XOR<Prisma.ServiceAccountUpdateManyMutationInput, Prisma.ServiceAccountUncheckedUpdateManyInput>
  /**
   * Filter which ServiceAccounts to update
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * Limit how many ServiceAccounts to update.
   */
  limit?: number
}

/**
 * ServiceAccount updateManyAndReturn
 */
export type ServiceAccountUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * The data used to update ServiceAccounts.
   */
  data: Prisma.XOR<Prisma.ServiceAccountUpdateManyMutationInput, Prisma.ServiceAccountUncheckedUpdateManyInput>
  /**
   * Filter which ServiceAccounts to update
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * Limit how many ServiceAccounts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ServiceAccount upsert
 */
export type ServiceAccountUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * The filter to search for the ServiceAccount to update in case it exists.
   */
  where: Prisma.ServiceAccountWhereUniqueInput
  /**
   * In case the ServiceAccount found by the `where` argument doesn't exist, create a new ServiceAccount with this data.
   */
  create: Prisma.XOR<Prisma.ServiceAccountCreateInput, Prisma.ServiceAccountUncheckedCreateInput>
  /**
   * In case the ServiceAccount was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ServiceAccountUpdateInput, Prisma.ServiceAccountUncheckedUpdateInput>
}

/**
 * ServiceAccount delete
 */
export type ServiceAccountDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  /**
   * Filter which ServiceAccount to delete.
   */
  where: Prisma.ServiceAccountWhereUniqueInput
}

/**
 * ServiceAccount deleteMany
 */
export type ServiceAccountDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ServiceAccounts to delete
   */
  where?: Prisma.ServiceAccountWhereInput
  /**
   * Limit how many ServiceAccounts to delete.
   */
  limit?: number
}

/**
 * ServiceAccount.garminProfiles
 */
export type ServiceAccount$garminProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  where?: Prisma.SyncProfileWhereInput
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  cursor?: Prisma.SyncProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SyncProfileScalarFieldEnum | Prisma.SyncProfileScalarFieldEnum[]
}

/**
 * ServiceAccount.trainerroadProfiles
 */
export type ServiceAccount$trainerroadProfilesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  where?: Prisma.SyncProfileWhereInput
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  cursor?: Prisma.SyncProfileWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SyncProfileScalarFieldEnum | Prisma.SyncProfileScalarFieldEnum[]
}

/**
 * ServiceAccount without action
 */
export type ServiceAccountDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
}
