
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SyncProfile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SyncProfile
 * 
 */
export type SyncProfileModel = runtime.Types.Result.DefaultSelection<Prisma.$SyncProfilePayload>

export type AggregateSyncProfile = {
  _count: SyncProfileCountAggregateOutputType | null
  _min: SyncProfileMinAggregateOutputType | null
  _max: SyncProfileMaxAggregateOutputType | null
}

export type SyncProfileMinAggregateOutputType = {
  id: string | null
  name: string | null
  ownerUserId: string | null
  withingsConfigDir: string | null
  garminAccountId: string | null
  trainerroadAccountId: string | null
  enabled: boolean | null
  enableBloodPressure: boolean | null
  scheduleCron: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SyncProfileMaxAggregateOutputType = {
  id: string | null
  name: string | null
  ownerUserId: string | null
  withingsConfigDir: string | null
  garminAccountId: string | null
  trainerroadAccountId: string | null
  enabled: boolean | null
  enableBloodPressure: boolean | null
  scheduleCron: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SyncProfileCountAggregateOutputType = {
  id: number
  name: number
  ownerUserId: number
  withingsConfigDir: number
  garminAccountId: number
  trainerroadAccountId: number
  enabled: number
  enableBloodPressure: number
  scheduleCron: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SyncProfileMinAggregateInputType = {
  id?: true
  name?: true
  ownerUserId?: true
  withingsConfigDir?: true
  garminAccountId?: true
  trainerroadAccountId?: true
  enabled?: true
  enableBloodPressure?: true
  scheduleCron?: true
  createdAt?: true
  updatedAt?: true
}

export type SyncProfileMaxAggregateInputType = {
  id?: true
  name?: true
  ownerUserId?: true
  withingsConfigDir?: true
  garminAccountId?: true
  trainerroadAccountId?: true
  enabled?: true
  enableBloodPressure?: true
  scheduleCron?: true
  createdAt?: true
  updatedAt?: true
}

export type SyncProfileCountAggregateInputType = {
  id?: true
  name?: true
  ownerUserId?: true
  withingsConfigDir?: true
  garminAccountId?: true
  trainerroadAccountId?: true
  enabled?: true
  enableBloodPressure?: true
  scheduleCron?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SyncProfileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncProfile to aggregate.
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncProfiles to fetch.
   */
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SyncProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SyncProfiles
  **/
  _count?: true | SyncProfileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SyncProfileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SyncProfileMaxAggregateInputType
}

export type GetSyncProfileAggregateType<T extends SyncProfileAggregateArgs> = {
      [P in keyof T & keyof AggregateSyncProfile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSyncProfile[P]>
    : Prisma.GetScalarType<T[P], AggregateSyncProfile[P]>
}




export type SyncProfileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncProfileWhereInput
  orderBy?: Prisma.SyncProfileOrderByWithAggregationInput | Prisma.SyncProfileOrderByWithAggregationInput[]
  by: Prisma.SyncProfileScalarFieldEnum[] | Prisma.SyncProfileScalarFieldEnum
  having?: Prisma.SyncProfileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SyncProfileCountAggregateInputType | true
  _min?: SyncProfileMinAggregateInputType
  _max?: SyncProfileMaxAggregateInputType
}

export type SyncProfileGroupByOutputType = {
  id: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId: string | null
  trainerroadAccountId: string | null
  enabled: boolean
  enableBloodPressure: boolean
  scheduleCron: string | null
  createdAt: Date
  updatedAt: Date
  _count: SyncProfileCountAggregateOutputType | null
  _min: SyncProfileMinAggregateOutputType | null
  _max: SyncProfileMaxAggregateOutputType | null
}

type GetSyncProfileGroupByPayload<T extends SyncProfileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SyncProfileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SyncProfileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SyncProfileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SyncProfileGroupByOutputType[P]>
      }
    >
  >



export type SyncProfileWhereInput = {
  AND?: Prisma.SyncProfileWhereInput | Prisma.SyncProfileWhereInput[]
  OR?: Prisma.SyncProfileWhereInput[]
  NOT?: Prisma.SyncProfileWhereInput | Prisma.SyncProfileWhereInput[]
  id?: Prisma.StringFilter<"SyncProfile"> | string
  name?: Prisma.StringFilter<"SyncProfile"> | string
  ownerUserId?: Prisma.StringFilter<"SyncProfile"> | string
  withingsConfigDir?: Prisma.StringFilter<"SyncProfile"> | string
  garminAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  trainerroadAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  enabled?: Prisma.BoolFilter<"SyncProfile"> | boolean
  enableBloodPressure?: Prisma.BoolFilter<"SyncProfile"> | boolean
  scheduleCron?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
  ownerUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  garminAccount?: Prisma.XOR<Prisma.ServiceAccountNullableScalarRelationFilter, Prisma.ServiceAccountWhereInput> | null
  trainerroadAccount?: Prisma.XOR<Prisma.ServiceAccountNullableScalarRelationFilter, Prisma.ServiceAccountWhereInput> | null
  runs?: Prisma.SyncRunListRelationFilter
}

export type SyncProfileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  withingsConfigDir?: Prisma.SortOrder
  garminAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  trainerroadAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  enableBloodPressure?: Prisma.SortOrder
  scheduleCron?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  ownerUser?: Prisma.UserOrderByWithRelationInput
  garminAccount?: Prisma.ServiceAccountOrderByWithRelationInput
  trainerroadAccount?: Prisma.ServiceAccountOrderByWithRelationInput
  runs?: Prisma.SyncRunOrderByRelationAggregateInput
}

export type SyncProfileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.SyncProfileWhereInput | Prisma.SyncProfileWhereInput[]
  OR?: Prisma.SyncProfileWhereInput[]
  NOT?: Prisma.SyncProfileWhereInput | Prisma.SyncProfileWhereInput[]
  name?: Prisma.StringFilter<"SyncProfile"> | string
  ownerUserId?: Prisma.StringFilter<"SyncProfile"> | string
  withingsConfigDir?: Prisma.StringFilter<"SyncProfile"> | string
  garminAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  trainerroadAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  enabled?: Prisma.BoolFilter<"SyncProfile"> | boolean
  enableBloodPressure?: Prisma.BoolFilter<"SyncProfile"> | boolean
  scheduleCron?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
  ownerUser?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  garminAccount?: Prisma.XOR<Prisma.ServiceAccountNullableScalarRelationFilter, Prisma.ServiceAccountWhereInput> | null
  trainerroadAccount?: Prisma.XOR<Prisma.ServiceAccountNullableScalarRelationFilter, Prisma.ServiceAccountWhereInput> | null
  runs?: Prisma.SyncRunListRelationFilter
}, "id">

export type SyncProfileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  withingsConfigDir?: Prisma.SortOrder
  garminAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  trainerroadAccountId?: Prisma.SortOrderInput | Prisma.SortOrder
  enabled?: Prisma.SortOrder
  enableBloodPressure?: Prisma.SortOrder
  scheduleCron?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SyncProfileCountOrderByAggregateInput
  _max?: Prisma.SyncProfileMaxOrderByAggregateInput
  _min?: Prisma.SyncProfileMinOrderByAggregateInput
}

export type SyncProfileScalarWhereWithAggregatesInput = {
  AND?: Prisma.SyncProfileScalarWhereWithAggregatesInput | Prisma.SyncProfileScalarWhereWithAggregatesInput[]
  OR?: Prisma.SyncProfileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SyncProfileScalarWhereWithAggregatesInput | Prisma.SyncProfileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SyncProfile"> | string
  name?: Prisma.StringWithAggregatesFilter<"SyncProfile"> | string
  ownerUserId?: Prisma.StringWithAggregatesFilter<"SyncProfile"> | string
  withingsConfigDir?: Prisma.StringWithAggregatesFilter<"SyncProfile"> | string
  garminAccountId?: Prisma.StringNullableWithAggregatesFilter<"SyncProfile"> | string | null
  trainerroadAccountId?: Prisma.StringNullableWithAggregatesFilter<"SyncProfile"> | string | null
  enabled?: Prisma.BoolWithAggregatesFilter<"SyncProfile"> | boolean
  enableBloodPressure?: Prisma.BoolWithAggregatesFilter<"SyncProfile"> | boolean
  scheduleCron?: Prisma.StringNullableWithAggregatesFilter<"SyncProfile"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SyncProfile"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SyncProfile"> | Date | string
}

export type SyncProfileCreateInput = {
  id?: string
  name: string
  withingsConfigDir: string
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerUser: Prisma.UserCreateNestedOneWithoutProfilesInput
  garminAccount?: Prisma.ServiceAccountCreateNestedOneWithoutGarminProfilesInput
  trainerroadAccount?: Prisma.ServiceAccountCreateNestedOneWithoutTrainerroadProfilesInput
  runs?: Prisma.SyncRunCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileUncheckedCreateInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId?: string | null
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  runs?: Prisma.SyncRunUncheckedCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
  garminAccount?: Prisma.ServiceAccountUpdateOneWithoutGarminProfilesNestedInput
  trainerroadAccount?: Prisma.ServiceAccountUpdateOneWithoutTrainerroadProfilesNestedInput
  runs?: Prisma.SyncRunUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runs?: Prisma.SyncRunUncheckedUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileCreateManyInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId?: string | null
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SyncProfileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncProfileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncProfileListRelationFilter = {
  every?: Prisma.SyncProfileWhereInput
  some?: Prisma.SyncProfileWhereInput
  none?: Prisma.SyncProfileWhereInput
}

export type SyncProfileOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type SyncProfileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  withingsConfigDir?: Prisma.SortOrder
  garminAccountId?: Prisma.SortOrder
  trainerroadAccountId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  enableBloodPressure?: Prisma.SortOrder
  scheduleCron?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncProfileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  withingsConfigDir?: Prisma.SortOrder
  garminAccountId?: Prisma.SortOrder
  trainerroadAccountId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  enableBloodPressure?: Prisma.SortOrder
  scheduleCron?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncProfileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerUserId?: Prisma.SortOrder
  withingsConfigDir?: Prisma.SortOrder
  garminAccountId?: Prisma.SortOrder
  trainerroadAccountId?: Prisma.SortOrder
  enabled?: Prisma.SortOrder
  enableBloodPressure?: Prisma.SortOrder
  scheduleCron?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SyncProfileScalarRelationFilter = {
  is?: Prisma.SyncProfileWhereInput
  isNot?: Prisma.SyncProfileWhereInput
}

export type SyncProfileCreateNestedManyWithoutOwnerUserInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput> | Prisma.SyncProfileCreateWithoutOwnerUserInput[] | Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput | Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput[]
  createMany?: Prisma.SyncProfileCreateManyOwnerUserInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileUncheckedCreateNestedManyWithoutOwnerUserInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput> | Prisma.SyncProfileCreateWithoutOwnerUserInput[] | Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput | Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput[]
  createMany?: Prisma.SyncProfileCreateManyOwnerUserInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileUpdateManyWithoutOwnerUserNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput> | Prisma.SyncProfileCreateWithoutOwnerUserInput[] | Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput | Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutOwnerUserInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutOwnerUserInput[]
  createMany?: Prisma.SyncProfileCreateManyOwnerUserInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutOwnerUserInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutOwnerUserInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutOwnerUserInput | Prisma.SyncProfileUpdateManyWithWhereWithoutOwnerUserInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type SyncProfileUncheckedUpdateManyWithoutOwnerUserNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput> | Prisma.SyncProfileCreateWithoutOwnerUserInput[] | Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput | Prisma.SyncProfileCreateOrConnectWithoutOwnerUserInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutOwnerUserInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutOwnerUserInput[]
  createMany?: Prisma.SyncProfileCreateManyOwnerUserInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutOwnerUserInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutOwnerUserInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutOwnerUserInput | Prisma.SyncProfileUpdateManyWithWhereWithoutOwnerUserInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type SyncProfileCreateNestedManyWithoutGarminAccountInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput> | Prisma.SyncProfileCreateWithoutGarminAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput | Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyGarminAccountInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileCreateNestedManyWithoutTrainerroadAccountInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput> | Prisma.SyncProfileCreateWithoutTrainerroadAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput | Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyTrainerroadAccountInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileUncheckedCreateNestedManyWithoutGarminAccountInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput> | Prisma.SyncProfileCreateWithoutGarminAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput | Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyGarminAccountInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileUncheckedCreateNestedManyWithoutTrainerroadAccountInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput> | Prisma.SyncProfileCreateWithoutTrainerroadAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput | Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyTrainerroadAccountInputEnvelope
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
}

export type SyncProfileUpdateManyWithoutGarminAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput> | Prisma.SyncProfileCreateWithoutGarminAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput | Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutGarminAccountInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutGarminAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyGarminAccountInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutGarminAccountInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutGarminAccountInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutGarminAccountInput | Prisma.SyncProfileUpdateManyWithWhereWithoutGarminAccountInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type SyncProfileUpdateManyWithoutTrainerroadAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput> | Prisma.SyncProfileCreateWithoutTrainerroadAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput | Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutTrainerroadAccountInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutTrainerroadAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyTrainerroadAccountInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutTrainerroadAccountInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutTrainerroadAccountInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutTrainerroadAccountInput | Prisma.SyncProfileUpdateManyWithWhereWithoutTrainerroadAccountInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type SyncProfileUncheckedUpdateManyWithoutGarminAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput> | Prisma.SyncProfileCreateWithoutGarminAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput | Prisma.SyncProfileCreateOrConnectWithoutGarminAccountInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutGarminAccountInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutGarminAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyGarminAccountInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutGarminAccountInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutGarminAccountInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutGarminAccountInput | Prisma.SyncProfileUpdateManyWithWhereWithoutGarminAccountInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput> | Prisma.SyncProfileCreateWithoutTrainerroadAccountInput[] | Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput[]
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput | Prisma.SyncProfileCreateOrConnectWithoutTrainerroadAccountInput[]
  upsert?: Prisma.SyncProfileUpsertWithWhereUniqueWithoutTrainerroadAccountInput | Prisma.SyncProfileUpsertWithWhereUniqueWithoutTrainerroadAccountInput[]
  createMany?: Prisma.SyncProfileCreateManyTrainerroadAccountInputEnvelope
  set?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  disconnect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  delete?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  connect?: Prisma.SyncProfileWhereUniqueInput | Prisma.SyncProfileWhereUniqueInput[]
  update?: Prisma.SyncProfileUpdateWithWhereUniqueWithoutTrainerroadAccountInput | Prisma.SyncProfileUpdateWithWhereUniqueWithoutTrainerroadAccountInput[]
  updateMany?: Prisma.SyncProfileUpdateManyWithWhereWithoutTrainerroadAccountInput | Prisma.SyncProfileUpdateManyWithWhereWithoutTrainerroadAccountInput[]
  deleteMany?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type SyncProfileCreateNestedOneWithoutRunsInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutRunsInput, Prisma.SyncProfileUncheckedCreateWithoutRunsInput>
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutRunsInput
  connect?: Prisma.SyncProfileWhereUniqueInput
}

export type SyncProfileUpdateOneRequiredWithoutRunsNestedInput = {
  create?: Prisma.XOR<Prisma.SyncProfileCreateWithoutRunsInput, Prisma.SyncProfileUncheckedCreateWithoutRunsInput>
  connectOrCreate?: Prisma.SyncProfileCreateOrConnectWithoutRunsInput
  upsert?: Prisma.SyncProfileUpsertWithoutRunsInput
  connect?: Prisma.SyncProfileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SyncProfileUpdateToOneWithWhereWithoutRunsInput, Prisma.SyncProfileUpdateWithoutRunsInput>, Prisma.SyncProfileUncheckedUpdateWithoutRunsInput>
}

export type SyncProfileCreateWithoutOwnerUserInput = {
  id?: string
  name: string
  withingsConfigDir: string
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  garminAccount?: Prisma.ServiceAccountCreateNestedOneWithoutGarminProfilesInput
  trainerroadAccount?: Prisma.ServiceAccountCreateNestedOneWithoutTrainerroadProfilesInput
  runs?: Prisma.SyncRunCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileUncheckedCreateWithoutOwnerUserInput = {
  id?: string
  name: string
  withingsConfigDir: string
  garminAccountId?: string | null
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  runs?: Prisma.SyncRunUncheckedCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileCreateOrConnectWithoutOwnerUserInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput>
}

export type SyncProfileCreateManyOwnerUserInputEnvelope = {
  data: Prisma.SyncProfileCreateManyOwnerUserInput | Prisma.SyncProfileCreateManyOwnerUserInput[]
}

export type SyncProfileUpsertWithWhereUniqueWithoutOwnerUserInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncProfileUpdateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedUpdateWithoutOwnerUserInput>
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedCreateWithoutOwnerUserInput>
}

export type SyncProfileUpdateWithWhereUniqueWithoutOwnerUserInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateWithoutOwnerUserInput, Prisma.SyncProfileUncheckedUpdateWithoutOwnerUserInput>
}

export type SyncProfileUpdateManyWithWhereWithoutOwnerUserInput = {
  where: Prisma.SyncProfileScalarWhereInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateManyMutationInput, Prisma.SyncProfileUncheckedUpdateManyWithoutOwnerUserInput>
}

export type SyncProfileScalarWhereInput = {
  AND?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
  OR?: Prisma.SyncProfileScalarWhereInput[]
  NOT?: Prisma.SyncProfileScalarWhereInput | Prisma.SyncProfileScalarWhereInput[]
  id?: Prisma.StringFilter<"SyncProfile"> | string
  name?: Prisma.StringFilter<"SyncProfile"> | string
  ownerUserId?: Prisma.StringFilter<"SyncProfile"> | string
  withingsConfigDir?: Prisma.StringFilter<"SyncProfile"> | string
  garminAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  trainerroadAccountId?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  enabled?: Prisma.BoolFilter<"SyncProfile"> | boolean
  enableBloodPressure?: Prisma.BoolFilter<"SyncProfile"> | boolean
  scheduleCron?: Prisma.StringNullableFilter<"SyncProfile"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SyncProfile"> | Date | string
}

export type SyncProfileCreateWithoutGarminAccountInput = {
  id?: string
  name: string
  withingsConfigDir: string
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerUser: Prisma.UserCreateNestedOneWithoutProfilesInput
  trainerroadAccount?: Prisma.ServiceAccountCreateNestedOneWithoutTrainerroadProfilesInput
  runs?: Prisma.SyncRunCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileUncheckedCreateWithoutGarminAccountInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  runs?: Prisma.SyncRunUncheckedCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileCreateOrConnectWithoutGarminAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput>
}

export type SyncProfileCreateManyGarminAccountInputEnvelope = {
  data: Prisma.SyncProfileCreateManyGarminAccountInput | Prisma.SyncProfileCreateManyGarminAccountInput[]
}

export type SyncProfileCreateWithoutTrainerroadAccountInput = {
  id?: string
  name: string
  withingsConfigDir: string
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerUser: Prisma.UserCreateNestedOneWithoutProfilesInput
  garminAccount?: Prisma.ServiceAccountCreateNestedOneWithoutGarminProfilesInput
  runs?: Prisma.SyncRunCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileUncheckedCreateWithoutTrainerroadAccountInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  runs?: Prisma.SyncRunUncheckedCreateNestedManyWithoutSyncProfileInput
}

export type SyncProfileCreateOrConnectWithoutTrainerroadAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput>
}

export type SyncProfileCreateManyTrainerroadAccountInputEnvelope = {
  data: Prisma.SyncProfileCreateManyTrainerroadAccountInput | Prisma.SyncProfileCreateManyTrainerroadAccountInput[]
}

export type SyncProfileUpsertWithWhereUniqueWithoutGarminAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncProfileUpdateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedUpdateWithoutGarminAccountInput>
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedCreateWithoutGarminAccountInput>
}

export type SyncProfileUpdateWithWhereUniqueWithoutGarminAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateWithoutGarminAccountInput, Prisma.SyncProfileUncheckedUpdateWithoutGarminAccountInput>
}

export type SyncProfileUpdateManyWithWhereWithoutGarminAccountInput = {
  where: Prisma.SyncProfileScalarWhereInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateManyMutationInput, Prisma.SyncProfileUncheckedUpdateManyWithoutGarminAccountInput>
}

export type SyncProfileUpsertWithWhereUniqueWithoutTrainerroadAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  update: Prisma.XOR<Prisma.SyncProfileUpdateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedUpdateWithoutTrainerroadAccountInput>
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedCreateWithoutTrainerroadAccountInput>
}

export type SyncProfileUpdateWithWhereUniqueWithoutTrainerroadAccountInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateWithoutTrainerroadAccountInput, Prisma.SyncProfileUncheckedUpdateWithoutTrainerroadAccountInput>
}

export type SyncProfileUpdateManyWithWhereWithoutTrainerroadAccountInput = {
  where: Prisma.SyncProfileScalarWhereInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateManyMutationInput, Prisma.SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountInput>
}

export type SyncProfileCreateWithoutRunsInput = {
  id?: string
  name: string
  withingsConfigDir: string
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  ownerUser: Prisma.UserCreateNestedOneWithoutProfilesInput
  garminAccount?: Prisma.ServiceAccountCreateNestedOneWithoutGarminProfilesInput
  trainerroadAccount?: Prisma.ServiceAccountCreateNestedOneWithoutTrainerroadProfilesInput
}

export type SyncProfileUncheckedCreateWithoutRunsInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId?: string | null
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SyncProfileCreateOrConnectWithoutRunsInput = {
  where: Prisma.SyncProfileWhereUniqueInput
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutRunsInput, Prisma.SyncProfileUncheckedCreateWithoutRunsInput>
}

export type SyncProfileUpsertWithoutRunsInput = {
  update: Prisma.XOR<Prisma.SyncProfileUpdateWithoutRunsInput, Prisma.SyncProfileUncheckedUpdateWithoutRunsInput>
  create: Prisma.XOR<Prisma.SyncProfileCreateWithoutRunsInput, Prisma.SyncProfileUncheckedCreateWithoutRunsInput>
  where?: Prisma.SyncProfileWhereInput
}

export type SyncProfileUpdateToOneWithWhereWithoutRunsInput = {
  where?: Prisma.SyncProfileWhereInput
  data: Prisma.XOR<Prisma.SyncProfileUpdateWithoutRunsInput, Prisma.SyncProfileUncheckedUpdateWithoutRunsInput>
}

export type SyncProfileUpdateWithoutRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
  garminAccount?: Prisma.ServiceAccountUpdateOneWithoutGarminProfilesNestedInput
  trainerroadAccount?: Prisma.ServiceAccountUpdateOneWithoutTrainerroadProfilesNestedInput
}

export type SyncProfileUncheckedUpdateWithoutRunsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncProfileCreateManyOwnerUserInput = {
  id?: string
  name: string
  withingsConfigDir: string
  garminAccountId?: string | null
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SyncProfileUpdateWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  garminAccount?: Prisma.ServiceAccountUpdateOneWithoutGarminProfilesNestedInput
  trainerroadAccount?: Prisma.ServiceAccountUpdateOneWithoutTrainerroadProfilesNestedInput
  runs?: Prisma.SyncRunUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runs?: Prisma.SyncRunUncheckedUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateManyWithoutOwnerUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncProfileCreateManyGarminAccountInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  trainerroadAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SyncProfileCreateManyTrainerroadAccountInput = {
  id?: string
  name: string
  ownerUserId: string
  withingsConfigDir: string
  garminAccountId?: string | null
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SyncProfileUpdateWithoutGarminAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
  trainerroadAccount?: Prisma.ServiceAccountUpdateOneWithoutTrainerroadProfilesNestedInput
  runs?: Prisma.SyncRunUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateWithoutGarminAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runs?: Prisma.SyncRunUncheckedUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateManyWithoutGarminAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  trainerroadAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SyncProfileUpdateWithoutTrainerroadAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ownerUser?: Prisma.UserUpdateOneRequiredWithoutProfilesNestedInput
  garminAccount?: Prisma.ServiceAccountUpdateOneWithoutGarminProfilesNestedInput
  runs?: Prisma.SyncRunUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateWithoutTrainerroadAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  runs?: Prisma.SyncRunUncheckedUpdateManyWithoutSyncProfileNestedInput
}

export type SyncProfileUncheckedUpdateManyWithoutTrainerroadAccountInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerUserId?: Prisma.StringFieldUpdateOperationsInput | string
  withingsConfigDir?: Prisma.StringFieldUpdateOperationsInput | string
  garminAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  enableBloodPressure?: Prisma.BoolFieldUpdateOperationsInput | boolean
  scheduleCron?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type SyncProfileCountOutputType
 */

export type SyncProfileCountOutputType = {
  runs: number
}

export type SyncProfileCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  runs?: boolean | SyncProfileCountOutputTypeCountRunsArgs
}

/**
 * SyncProfileCountOutputType without action
 */
export type SyncProfileCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfileCountOutputType
   */
  select?: Prisma.SyncProfileCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SyncProfileCountOutputType without action
 */
export type SyncProfileCountOutputTypeCountRunsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SyncRunWhereInput
}


export type SyncProfileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerUserId?: boolean
  withingsConfigDir?: boolean
  garminAccountId?: boolean
  trainerroadAccountId?: boolean
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
  runs?: boolean | Prisma.SyncProfile$runsArgs<ExtArgs>
  _count?: boolean | Prisma.SyncProfileCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["syncProfile"]>

export type SyncProfileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerUserId?: boolean
  withingsConfigDir?: boolean
  garminAccountId?: boolean
  trainerroadAccountId?: boolean
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
}, ExtArgs["result"]["syncProfile"]>

export type SyncProfileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerUserId?: boolean
  withingsConfigDir?: boolean
  garminAccountId?: boolean
  trainerroadAccountId?: boolean
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
}, ExtArgs["result"]["syncProfile"]>

export type SyncProfileSelectScalar = {
  id?: boolean
  name?: boolean
  ownerUserId?: boolean
  withingsConfigDir?: boolean
  garminAccountId?: boolean
  trainerroadAccountId?: boolean
  enabled?: boolean
  enableBloodPressure?: boolean
  scheduleCron?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SyncProfileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "ownerUserId" | "withingsConfigDir" | "garminAccountId" | "trainerroadAccountId" | "enabled" | "enableBloodPressure" | "scheduleCron" | "createdAt" | "updatedAt", ExtArgs["result"]["syncProfile"]>
export type SyncProfileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
  runs?: boolean | Prisma.SyncProfile$runsArgs<ExtArgs>
  _count?: boolean | Prisma.SyncProfileCountOutputTypeDefaultArgs<ExtArgs>
}
export type SyncProfileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
}
export type SyncProfileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownerUser?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  garminAccount?: boolean | Prisma.SyncProfile$garminAccountArgs<ExtArgs>
  trainerroadAccount?: boolean | Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>
}

export type $SyncProfilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SyncProfile"
  objects: {
    ownerUser: Prisma.$UserPayload<ExtArgs>
    garminAccount: Prisma.$ServiceAccountPayload<ExtArgs> | null
    trainerroadAccount: Prisma.$ServiceAccountPayload<ExtArgs> | null
    runs: Prisma.$SyncRunPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    ownerUserId: string
    withingsConfigDir: string
    garminAccountId: string | null
    trainerroadAccountId: string | null
    enabled: boolean
    enableBloodPressure: boolean
    scheduleCron: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["syncProfile"]>
  composites: {}
}

export type SyncProfileGetPayload<S extends boolean | null | undefined | SyncProfileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload, S>

export type SyncProfileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SyncProfileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SyncProfileCountAggregateInputType | true
  }

export interface SyncProfileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SyncProfile'], meta: { name: 'SyncProfile' } }
  /**
   * Find zero or one SyncProfile that matches the filter.
   * @param {SyncProfileFindUniqueArgs} args - Arguments to find a SyncProfile
   * @example
   * // Get one SyncProfile
   * const syncProfile = await prisma.syncProfile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SyncProfileFindUniqueArgs>(args: Prisma.SelectSubset<T, SyncProfileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SyncProfile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SyncProfileFindUniqueOrThrowArgs} args - Arguments to find a SyncProfile
   * @example
   * // Get one SyncProfile
   * const syncProfile = await prisma.syncProfile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SyncProfileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SyncProfileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncProfile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileFindFirstArgs} args - Arguments to find a SyncProfile
   * @example
   * // Get one SyncProfile
   * const syncProfile = await prisma.syncProfile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SyncProfileFindFirstArgs>(args?: Prisma.SelectSubset<T, SyncProfileFindFirstArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SyncProfile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileFindFirstOrThrowArgs} args - Arguments to find a SyncProfile
   * @example
   * // Get one SyncProfile
   * const syncProfile = await prisma.syncProfile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SyncProfileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SyncProfileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SyncProfiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SyncProfiles
   * const syncProfiles = await prisma.syncProfile.findMany()
   * 
   * // Get first 10 SyncProfiles
   * const syncProfiles = await prisma.syncProfile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const syncProfileWithIdOnly = await prisma.syncProfile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SyncProfileFindManyArgs>(args?: Prisma.SelectSubset<T, SyncProfileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SyncProfile.
   * @param {SyncProfileCreateArgs} args - Arguments to create a SyncProfile.
   * @example
   * // Create one SyncProfile
   * const SyncProfile = await prisma.syncProfile.create({
   *   data: {
   *     // ... data to create a SyncProfile
   *   }
   * })
   * 
   */
  create<T extends SyncProfileCreateArgs>(args: Prisma.SelectSubset<T, SyncProfileCreateArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SyncProfiles.
   * @param {SyncProfileCreateManyArgs} args - Arguments to create many SyncProfiles.
   * @example
   * // Create many SyncProfiles
   * const syncProfile = await prisma.syncProfile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SyncProfileCreateManyArgs>(args?: Prisma.SelectSubset<T, SyncProfileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SyncProfiles and returns the data saved in the database.
   * @param {SyncProfileCreateManyAndReturnArgs} args - Arguments to create many SyncProfiles.
   * @example
   * // Create many SyncProfiles
   * const syncProfile = await prisma.syncProfile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SyncProfiles and only return the `id`
   * const syncProfileWithIdOnly = await prisma.syncProfile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SyncProfileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SyncProfileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SyncProfile.
   * @param {SyncProfileDeleteArgs} args - Arguments to delete one SyncProfile.
   * @example
   * // Delete one SyncProfile
   * const SyncProfile = await prisma.syncProfile.delete({
   *   where: {
   *     // ... filter to delete one SyncProfile
   *   }
   * })
   * 
   */
  delete<T extends SyncProfileDeleteArgs>(args: Prisma.SelectSubset<T, SyncProfileDeleteArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SyncProfile.
   * @param {SyncProfileUpdateArgs} args - Arguments to update one SyncProfile.
   * @example
   * // Update one SyncProfile
   * const syncProfile = await prisma.syncProfile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SyncProfileUpdateArgs>(args: Prisma.SelectSubset<T, SyncProfileUpdateArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SyncProfiles.
   * @param {SyncProfileDeleteManyArgs} args - Arguments to filter SyncProfiles to delete.
   * @example
   * // Delete a few SyncProfiles
   * const { count } = await prisma.syncProfile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SyncProfileDeleteManyArgs>(args?: Prisma.SelectSubset<T, SyncProfileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SyncProfiles
   * const syncProfile = await prisma.syncProfile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SyncProfileUpdateManyArgs>(args: Prisma.SelectSubset<T, SyncProfileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SyncProfiles and returns the data updated in the database.
   * @param {SyncProfileUpdateManyAndReturnArgs} args - Arguments to update many SyncProfiles.
   * @example
   * // Update many SyncProfiles
   * const syncProfile = await prisma.syncProfile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SyncProfiles and only return the `id`
   * const syncProfileWithIdOnly = await prisma.syncProfile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SyncProfileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SyncProfileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SyncProfile.
   * @param {SyncProfileUpsertArgs} args - Arguments to update or create a SyncProfile.
   * @example
   * // Update or create a SyncProfile
   * const syncProfile = await prisma.syncProfile.upsert({
   *   create: {
   *     // ... data to create a SyncProfile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SyncProfile we want to update
   *   }
   * })
   */
  upsert<T extends SyncProfileUpsertArgs>(args: Prisma.SelectSubset<T, SyncProfileUpsertArgs<ExtArgs>>): Prisma.Prisma__SyncProfileClient<runtime.Types.Result.GetResult<Prisma.$SyncProfilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SyncProfiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileCountArgs} args - Arguments to filter SyncProfiles to count.
   * @example
   * // Count the number of SyncProfiles
   * const count = await prisma.syncProfile.count({
   *   where: {
   *     // ... the filter for the SyncProfiles we want to count
   *   }
   * })
  **/
  count<T extends SyncProfileCountArgs>(
    args?: Prisma.Subset<T, SyncProfileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SyncProfileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SyncProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SyncProfileAggregateArgs>(args: Prisma.Subset<T, SyncProfileAggregateArgs>): Prisma.PrismaPromise<GetSyncProfileAggregateType<T>>

  /**
   * Group by SyncProfile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SyncProfileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SyncProfileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SyncProfileGroupByArgs['orderBy'] }
      : { orderBy?: SyncProfileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SyncProfileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSyncProfileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SyncProfile model
 */
readonly fields: SyncProfileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SyncProfile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SyncProfileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ownerUser<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  garminAccount<T extends Prisma.SyncProfile$garminAccountArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncProfile$garminAccountArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  trainerroadAccount<T extends Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncProfile$trainerroadAccountArgs<ExtArgs>>): Prisma.Prisma__ServiceAccountClient<runtime.Types.Result.GetResult<Prisma.$ServiceAccountPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  runs<T extends Prisma.SyncProfile$runsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SyncProfile$runsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SyncRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SyncProfile model
 */
export interface SyncProfileFieldRefs {
  readonly id: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly name: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly ownerUserId: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly withingsConfigDir: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly garminAccountId: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly trainerroadAccountId: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly enabled: Prisma.FieldRef<"SyncProfile", 'Boolean'>
  readonly enableBloodPressure: Prisma.FieldRef<"SyncProfile", 'Boolean'>
  readonly scheduleCron: Prisma.FieldRef<"SyncProfile", 'String'>
  readonly createdAt: Prisma.FieldRef<"SyncProfile", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SyncProfile", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SyncProfile findUnique
 */
export type SyncProfileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter, which SyncProfile to fetch.
   */
  where: Prisma.SyncProfileWhereUniqueInput
}

/**
 * SyncProfile findUniqueOrThrow
 */
export type SyncProfileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter, which SyncProfile to fetch.
   */
  where: Prisma.SyncProfileWhereUniqueInput
}

/**
 * SyncProfile findFirst
 */
export type SyncProfileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter, which SyncProfile to fetch.
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncProfiles to fetch.
   */
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncProfiles.
   */
  cursor?: Prisma.SyncProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncProfiles.
   */
  distinct?: Prisma.SyncProfileScalarFieldEnum | Prisma.SyncProfileScalarFieldEnum[]
}

/**
 * SyncProfile findFirstOrThrow
 */
export type SyncProfileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter, which SyncProfile to fetch.
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncProfiles to fetch.
   */
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SyncProfiles.
   */
  cursor?: Prisma.SyncProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncProfiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SyncProfiles.
   */
  distinct?: Prisma.SyncProfileScalarFieldEnum | Prisma.SyncProfileScalarFieldEnum[]
}

/**
 * SyncProfile findMany
 */
export type SyncProfileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter, which SyncProfiles to fetch.
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SyncProfiles to fetch.
   */
  orderBy?: Prisma.SyncProfileOrderByWithRelationInput | Prisma.SyncProfileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SyncProfiles.
   */
  cursor?: Prisma.SyncProfileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SyncProfiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SyncProfiles.
   */
  skip?: number
  distinct?: Prisma.SyncProfileScalarFieldEnum | Prisma.SyncProfileScalarFieldEnum[]
}

/**
 * SyncProfile create
 */
export type SyncProfileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * The data needed to create a SyncProfile.
   */
  data: Prisma.XOR<Prisma.SyncProfileCreateInput, Prisma.SyncProfileUncheckedCreateInput>
}

/**
 * SyncProfile createMany
 */
export type SyncProfileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SyncProfiles.
   */
  data: Prisma.SyncProfileCreateManyInput | Prisma.SyncProfileCreateManyInput[]
}

/**
 * SyncProfile createManyAndReturn
 */
export type SyncProfileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * The data used to create many SyncProfiles.
   */
  data: Prisma.SyncProfileCreateManyInput | Prisma.SyncProfileCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * SyncProfile update
 */
export type SyncProfileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * The data needed to update a SyncProfile.
   */
  data: Prisma.XOR<Prisma.SyncProfileUpdateInput, Prisma.SyncProfileUncheckedUpdateInput>
  /**
   * Choose, which SyncProfile to update.
   */
  where: Prisma.SyncProfileWhereUniqueInput
}

/**
 * SyncProfile updateMany
 */
export type SyncProfileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SyncProfiles.
   */
  data: Prisma.XOR<Prisma.SyncProfileUpdateManyMutationInput, Prisma.SyncProfileUncheckedUpdateManyInput>
  /**
   * Filter which SyncProfiles to update
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * Limit how many SyncProfiles to update.
   */
  limit?: number
}

/**
 * SyncProfile updateManyAndReturn
 */
export type SyncProfileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * The data used to update SyncProfiles.
   */
  data: Prisma.XOR<Prisma.SyncProfileUpdateManyMutationInput, Prisma.SyncProfileUncheckedUpdateManyInput>
  /**
   * Filter which SyncProfiles to update
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * Limit how many SyncProfiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * SyncProfile upsert
 */
export type SyncProfileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * The filter to search for the SyncProfile to update in case it exists.
   */
  where: Prisma.SyncProfileWhereUniqueInput
  /**
   * In case the SyncProfile found by the `where` argument doesn't exist, create a new SyncProfile with this data.
   */
  create: Prisma.XOR<Prisma.SyncProfileCreateInput, Prisma.SyncProfileUncheckedCreateInput>
  /**
   * In case the SyncProfile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SyncProfileUpdateInput, Prisma.SyncProfileUncheckedUpdateInput>
}

/**
 * SyncProfile delete
 */
export type SyncProfileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
  /**
   * Filter which SyncProfile to delete.
   */
  where: Prisma.SyncProfileWhereUniqueInput
}

/**
 * SyncProfile deleteMany
 */
export type SyncProfileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SyncProfiles to delete
   */
  where?: Prisma.SyncProfileWhereInput
  /**
   * Limit how many SyncProfiles to delete.
   */
  limit?: number
}

/**
 * SyncProfile.garminAccount
 */
export type SyncProfile$garminAccountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  where?: Prisma.ServiceAccountWhereInput
}

/**
 * SyncProfile.trainerroadAccount
 */
export type SyncProfile$trainerroadAccountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ServiceAccount
   */
  select?: Prisma.ServiceAccountSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ServiceAccount
   */
  omit?: Prisma.ServiceAccountOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ServiceAccountInclude<ExtArgs> | null
  where?: Prisma.ServiceAccountWhereInput
}

/**
 * SyncProfile.runs
 */
export type SyncProfile$runsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncRun
   */
  select?: Prisma.SyncRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncRun
   */
  omit?: Prisma.SyncRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncRunInclude<ExtArgs> | null
  where?: Prisma.SyncRunWhereInput
  orderBy?: Prisma.SyncRunOrderByWithRelationInput | Prisma.SyncRunOrderByWithRelationInput[]
  cursor?: Prisma.SyncRunWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SyncRunScalarFieldEnum | Prisma.SyncRunScalarFieldEnum[]
}

/**
 * SyncProfile without action
 */
export type SyncProfileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SyncProfile
   */
  select?: Prisma.SyncProfileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SyncProfile
   */
  omit?: Prisma.SyncProfileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SyncProfileInclude<ExtArgs> | null
}
